### ISSUE TITLE
Commit to static typing

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#173]
It's well known that static typing reduces bugs. Python is by it's nature a dynamic language and does well from this.
However, I think we can have the best of both worlds by saying that our code should be statically typed.
What I mean by this is that we use type hinting in all our production code, and have a tool enforce that.

An added and quite significant bonus is that the editor is then able to accurately autocomplete your code for you, and also tell you early if you've done something wrong!

As the project grows and has more contributors, type safety becomes more important.
This is pretty equivalent to [why you should use Typescript for large projects in the Javascript world](https://serokell.io/blog/why-typescript).

**Describe the solution you'd like**
Type hinting on all production code, enforced with: [PyRight](https://github.com/microsoft/pyright)
VS Code's (PyLance)[https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance] extension uses PyRight under the hood.

Let's make this part of our CI pipeline, forcing type safety, we're already most of the way there anyway!
We can start with the gentler option that only says that functions with defined types are type checked, and then later switch to strict typing where all functions MUST have type signatures.

Let's not have our unit tests type checked though. Dynamic programming does have it's advantages!

**Comment by Pixep** [comment]
Absolutely, if you have time, please go ahead and add it!
