### ISSUE TITLE
Installing `pluma` may not make it available in the PATH

### ISSUE THREAD

**Issue by Pixep** [Witekio/pluma-automation#35]
When running `./install.sh`, it can be installed in a location not in the PATH, making it very unclear why `pluma` does not work afterwards.

**Comment by Zematus** [comment]
I think the warning that `install.sh` displays regarding `local/bin` not being in PATH is good enough. It should fall on the user correcting this issue on their dev environment.

**Comment by mjftw** [comment]
> I think the warning that `install.sh` displays regarding `local/bin` not being in PATH is good enough. It should fall on the user correcting this issue on their dev environment.

Yeah I think you're right.
In that case I'll mark this issue as "wontfix" and close it.
