### ISSUE TITLE
Move documentation site somewhere publically accessible

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#46]
**Is your feature request related to a problem? Please describe.**
The documentation site is currently inaccessible due to the project moving from private to public.
The docs need to be somewhere accessible by external people, without access to the Witekio private network.

**Describe the solution you'd like**
Documentation site moved to and hosted at www.readthedocs.com

**Comment by philprobinson84** [comment]
I think the readthedocs suggestion will cost $150 per month. Public hosting would be significantly less. What value does readthedocs bring to justify the additional expense?

**Comment by Pixep** [comment]
Really? I don't know readthedocs, but from their website:

> Free docs hosting
> We will host your documentation for free forever. There are no tricks. We help tens of thousands of open source projects share their docs.
