### ISSUE TITLE
Show additional test info when running "pluma check/list" 

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#96]
**Is your feature request related to a problem? Please describe.**
As an enhancement to `pluma test` I'd like to get some info alongside the available tests list. 

Current:
```
pluma --plugin ./myplugindir check

Device actions:
    [x] {'copytodevice'}
          {"file": "/home/merlin/projects/pluma-automation/README.md", "destination": "/tmp/", "timeout": 10}

Core tests (testsuite, Python):
    [x] mytests.SayHello
    [ ] testsuite.kernel.KernelModulesLoaded
    [ ] testsuite.memory.MemorySize
    [ ] testsuite.networking.IperfBandwidth
    [ ] testsuite.networking.NetworkingTestBase
    [ ] testsuite.networking.RespondsToPing
```

**Describe the solution you'd like**
I'd like to see something like the following, with an entirely new sub-command `pluma list`:

```
pluma --plugin ./myplugindir list

Device actions:
    [x] {'copytodevice'}
          {"file": "/home/merlin/projects/pluma-automation/README.md", "destination": "/tmp/", "timeout": 10}

Core tests (testsuite, Python):
    [x] mytests.SayHello
            Print a hello message
    [ ] testsuite.kernel.KernelModulesLoaded
            Check whether certain kernel modules are installed
    [ ] testsuite.memory.MemorySize
            Check the memory of the target
    [ ] testsuite.networking.IperfBandwidth
    [ ] testsuite.networking.NetworkingTestBase
    [ ] testsuite.networking.RespondsToPing
```

This info could easily be pulled from the Test docstrings, and this would encourage people to actually write docstrings.
Maybe just the first line of the docstring here.

To take this one step further, it would be good to be able to query individual tests to see what there parameters are.
We'd display the full docstring here.

```
pluma list mytests

Core tests (testsuite, Python):
    [x] mytests.SayHello
            Print a hello message
    [ ] mytests.SomeOtherTest
            Really amazing docstring
```

```
pluma list mytests.SayHello
mytests.SayHello: selected
        Print a hello message
        Here's some other info that I put in the docstrings
        And some more!

Parameters:
        name (str)
        how_many_times (int)
```

The types for parameters could be pulled from the type hints in the `__init__` function.
It would be great if we could add a description of each parameter, but not sure there's a natural place to put this in the class without having to do an ugly docstring or something.

All of this would make adding new tests via the `--plugin` flag much more appealing to users, as they'd get instant feedback that it worked. We get documentation for free, and it encourages people to follow best practice in their tests with docstrings and type hints, meaning we should get better code too.

**Comment by Zematus** [comment]
There's already a command 'tests' which generates a list of all tests (though without the amount of detail requested). Should we replace 'tests' with 'list' since it seems redundant?

**Comment by Pixep** [comment]
Yeah I didn't catch that, but the issue is incorrect regrading that. Either we stick with `tests` (analog to `docker images`), or rename it to `list`. But we don't need two commands for that. I'd recommend sticking with `tests` to address one thing at a time, but not opposed to renaming it.

**Comment by Zematus** [comment]
Currently, the list of tests can display multiple test types (python, shell, actions, etc). The docstring can be used for core tests and actions, but what about shell tests? what kind of description can be added to them that isn't just a generic "this is an inline shell test" since they are defined directly in the yml file?

Also, what should be displayed for tests that appear multiple times but with different parameters? should it display the same description for each one of them? Or maybe just for the first instance?
